include: "rules/common.smk"
include: "rules/create_links.smk"
include: "rules/contamination.smk"
include: "rules/mutation_calling.smk"
include: "rules/post_processing.smk"
include: "rules/annovar.smk"


container: "docker://condaforge/mambaforge"


rule all:
    input:
        wrkdir / str(output_prefix + "_filtered.vcf"),
        wrkdir / str(output_prefix + "_filtered.vcf.idx"),
        wrkdir / str(output_prefix + "_filtered.vcf.filteringStats.tsv"),
        wrkdir / str(output_prefix + ".crosscheck_metrics") if normal else [],
        wrkdir / str(output_prefix + "_filtered.avinput.hg19_multianno.csv")
        if run_annovar
        else [],
