jobs: 10
latency-wait: 60
reason: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 2

# Slurm default resources (Uncomment and modify for your cluster)
default-resources:
  - partition="your_cluster_partition"
# - slurm="exclude=compute[011-013]"

# MUST BE ABSOLUTE PATHS
conda-prefix: /absolute/path/to/somatic_variant_caller/conda_env_singularity
singularity-prefix: /absolute/path/to/somatic_variant_caller/Singularity

# Modify this for the bindings Singularity needs on your HPC
singularity-args: "-B /:/"
